/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.petuska.klip.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'klip.greeting' plugin.
 */
class KlipPluginTest {
  @Test
  fun `plugin registers task`() {
    val project = ProjectBuilder.builder().build()
    project.plugins.apply("dev.petuska.klip")

    assertNotNull(project.extensions.findByName("klip"))
  }
}
